version: '3.4'
services:
  cmake-build:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/app
    command: ["cmake", "--build", "."]
  cmake-run:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/app
    command: ["./DockerTests"]